### ISSUE TITLE
Field-test Fetch prototype app in home areas

### ISSUE THREAD

**Issue by nakaz** [devleague/eat-this#23]
Keahi and Mete pointed out about field-testing the application in our respective areas or wherever we are when we get the chance to see how our app queries Yelp for venues in the area. 

~~Make sure to source the .env file before starting up!~~

UPDATE: Commit 04385047554e1673968fe191796303584c1ecb71 resolves having to source .env file before start up with `npm run dev`. HAPPY WORKFLOW!

(But please pull the latest commit regardless).

@Keahibono (Kailua)
@oteswang (Kapolei/Makakilo)
@julzbond (Kamuki/Kapahulu)
@senakamura (Kaimuki/Kahala) 

And other places. Have fun querying!

**Comment by nakaz** [comment]
Sean checking in, and it totally works in my area! Getting all the foodie places to go and I'm getting hungry at this hour!

**Comment by nakaz** [comment]
Shoutout to @thgaskell for being our first alpha tester on location querying! THANKS TONY!

**Comment by Keahibono** [comment]
Works....close it1
