### ISSUE TITLE
Clean up GET errors for Google Maps API 

### ISSUE THREAD

**Issue by nakaz** [devleague/eat-this#42]
![screen shot 2015-10-05 at 8 46 43 pm](https://cloud.githubusercontent.com/assets/2155125/10302014/e36f38ce-6ba3-11e5-8db9-311b7a04c7d5.png)
![screen shot 2015-10-05 at 8 46 16 pm](https://cloud.githubusercontent.com/assets/2155125/10302015/e36f5976-6ba3-11e5-945c-e38e2e238da2.png)
![screen shot 2015-10-05 at 8 58 24 pm](https://cloud.githubusercontent.com/assets/2155125/10302016/e3708daa-6ba3-11e5-9db5-b4986934e146.png)

**Comment by julzbond** [comment]
@senakamura looking into this but I'm not getting the same error and I also don't have an API included. After doing some initial research, wondering if you have an ad blocker on that is blocking it, and if the errors will clear up if you disable it?

**Comment by nakaz** [comment]
Issue is with adblocker
