### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by Keahibono** [devleague/eat-this#5]

**Comment by nakaz** [comment]
Basic SCSS and Gulp watch has been built with gulp-scss commit

**Comment by theRemix** [comment]
@senakamura make sure to commit and push your code up.
in your commit message, you can include "resolves #5" to reference and close this ticket

**Comment by nakaz** [comment]
Basic SCSS has be resolved with ionic commits. Will make new issue regarding future design work.
