### ISSUE TITLE
Swiping, Angular Mix

### ISSUE THREAD

**Issue by Keahibono** [devleague/eat-this#6]

**Comment by Keahibono** [comment]
https://docs.angularjs.org/api/ngTouch/directive/ngSwipeLeft

**Comment by Keahibono** [comment]
http://onehungrymind.com/build-sweet-angularjs-photo-slider-pt-2-ngtouch/
http://jsfiddle.net/scottux/RLDsU/
https://github.com/marceloklein/ionic-contrib-swipe-cards/blob/horizontal_swipe/ionic.swipecards.js
https://codeforgeek.com/2014/12/swipe-to-delete-implementation-using-angular/

**Comment by nakaz** [comment]
Hey @Keahibono this issue appears to be resolved. You can close it if you feel you have completed it.

**Comment by Keahibono** [comment]
Swiping function is good....still need to delete from array and show details for 'saves'
